// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdrM5Y6rToGljrtuhPSMUEpaQ8Hkeye70',
    appId: '1:174212437230:web:690243567b25e04e130fff',
    messagingSenderId: '174212437230',
    projectId: 'fluttertiktokclone-35dc3',
    authDomain: 'fluttertiktokclone-35dc3.firebaseapp.com',
    storageBucket: 'fluttertiktokclone-35dc3.appspot.com',
    measurementId: 'G-J5CDZCCMQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs9YD7Xsgmc-amPizG6JH_g6DBUr2V2WU',
    appId: '1:174212437230:android:6e379b78278e902e130fff',
    messagingSenderId: '174212437230',
    projectId: 'fluttertiktokclone-35dc3',
    storageBucket: 'fluttertiktokclone-35dc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB06nr3qHWeLdvgZ6pdC_CIiYLIKJM7dGc',
    appId: '1:174212437230:ios:c36e5896cac2182e130fff',
    messagingSenderId: '174212437230',
    projectId: 'fluttertiktokclone-35dc3',
    storageBucket: 'fluttertiktokclone-35dc3.appspot.com',
    iosBundleId: 'com.example.flutterTiktokClone',
  );
}
